"""
post_to_instagram.py

Post a photo/video to Instagram, either right now or on a schedule.
- The MEDIA is picked from a folder (POST_DIR): the first file in name order.
- The CAPTION is generated by Groq (vision model for images, text model for videos).
- After a successful post, the file is moved to POSTED_DIR so it isn't posted twice.
- Schedule times are interpreted in Asia/Jakarta (WIB).

Folder layout:
    posts/       <- drop the files you want to post here (jpg, jpeg, png, mp4, mov)
    posted/      <- created automatically, files land here after posting

Usage:
    python post_to_instagram.py                          # post the next file right now
    python post_to_instagram.py --at "2026-10-01 19:30"  # wait until that time (WIB), then post
    python post_to_instagram.py --daily 19:30            # post one file every day at 19:30 WIB
    python post_to_instagram.py --daily 19:30 --jitter 10  # ...at a random time +/- 10 minutes
    python post_to_instagram.py --dry-run                # generate + print the caption, don't post
    python post_to_instagram.py --hint "sunset in Bali"  # give the caption model extra context
    python post_to_instagram.py --caption "my own text"  # skip AI, use this caption
    python post_to_instagram.py --reel                   # post .mp4/.mov as a Reel

NOTE: scheduling is done by this process staying alive (it sleeps until the
target time). Keep it running (tmux/screen/systemd), or use cron/Task Scheduler
with the plain "post right now" mode instead.
"""

import argparse
import base64
import os
import random
import re
import shutil
import sys
import time
from datetime import datetime, timedelta
from pathlib import Path
from zoneinfo import ZoneInfo

from groq import Groq
from instagrapi import Client
from instagrapi.exceptions import ClientError, FeedbackRequired, PleaseWaitFewMinutes
from PIL import Image

import shared_context   # keep shared_context.py in the same folder
import ig_session        # keep ig_session.py in the same folder

# Credentials are read from environment variables (don't hardcode secrets in source).
#   export IG_PASSWORD="..."   export GROQ_API_KEY="..."
IG_USERNAME = os.environ.get("IG_USERNAME", "feliciaaa_kim")
IG_PASSWORD = os.environ.get("IG_PASSWORD", "")
GROQ_API_KEY = os.environ.get("GROQ_API_KEY", "")
# Optional: the "sessionid" cookie from a browser where you're logged in to instagram.com.
# Used only if password login is blocked ("Your version of Instagram is out of date").
IG_SESSIONID = os.environ.get("IG_SESSIONID", "")

SESSION_FILE = "session.json"
POST_DIR = Path("posts")
POSTED_DIR = Path("posted")
TMP_JPG_PATH = Path("tmp_upload.jpg")
LOCAL_TZ = ZoneInfo("Asia/Jakarta")

VISION_MODEL = "qwen/qwen3.8-27b"     # same vision model as auto_like_comment.py
TEXT_MODEL = "openai/gpt-oss-20b"     # used for videos (no frame analysis)

IMAGE_EXTS = {".jpg", ".jpeg", ".png"}
VIDEO_EXTS = {".mp4", ".mov"}

CAPTION_SYSTEM_PROMPT = """
You write Instagram captions in English for the account owner.

Rules:
- Base the caption on what's actually in the media (and the hint, if given). Be specific, not generic.
- 1 to 3 short sentences, casual and natural, like a real person posting — not marketing copy.
- Warm and a little playful. No cringe influencer phrases, no "Hey guys!".
- At most 2 emojis in total.
- {hashtag_rule}
- Output ONLY the caption text: no quotation marks, no markdown, no preface like "Here's a caption".
"""


# ---------- helpers ----------

def natural_key(path):
    """Sort 'post2.jpg' before 'post10.jpg'."""
    return [int(t) if t.isdigit() else t.lower() for t in re.split(r"(\d+)", path.name)]


def pick_next_media():
    """First supported file in POST_DIR (name order), or None if the folder is empty."""
    POST_DIR.mkdir(exist_ok=True)
    files = [
        p for p in POST_DIR.iterdir()
        if p.is_file() and p.suffix.lower() in IMAGE_EXTS | VIDEO_EXTS
    ]
    if not files:
        return None
    files.sort(key=natural_key)
    return files[0]


def strip_reasoning(text):
    """Remove <think>...</think> blocks some models emit, plus stray quotes."""
    text = re.sub(r"<think>.*?</think>", "", text or "", flags=re.DOTALL)
    return text.strip().strip('"').strip()


def to_jpeg(src_path):
    """Instagram photo uploads are safest as RGB JPEG. Convert (also handles PNG)."""
    with Image.open(src_path) as im:
        im.convert("RGB").save(TMP_JPG_PATH, "JPEG", quality=95)
    return TMP_JPG_PATH


# ---------- caption generation ----------

def generate_caption(groq_client, media_path, hint=None, hashtags=True):
    hashtag_rule = (
        "Add 3 to 5 relevant hashtags on a new line at the end."
        if hashtags else "Do not use hashtags."
    )
    system_prompt = CAPTION_SYSTEM_PROMPT.format(hashtag_rule=hashtag_rule)
    hint_text = f"Extra context from the account owner: {hint}" if hint else "No extra context given."

    if media_path.suffix.lower() in IMAGE_EXTS:
        jpg_path = to_jpeg(media_path)
        with open(jpg_path, "rb") as f:
            b64 = base64.b64encode(f.read()).decode("utf-8")

        resp = groq_client.chat.completions.create(
            model=VISION_MODEL,
            messages=[
                {"role": "system", "content": system_prompt},
                {
                    "role": "user",
                    "content": [
                        {"type": "text", "text": f"Write a caption for this photo. {hint_text}"},
                        {"type": "image_url", "image_url": {"url": f"data:image/jpeg;base64,{b64}"}},
                    ],
                },
            ],
            temperature=0.9,
            max_completion_tokens=250,
        )
    else:
        # Video: no frame analysis here, so lean on the filename + hint.
        resp = groq_client.chat.completions.create(
            model=TEXT_MODEL,
            messages=[
                {"role": "system", "content": system_prompt},
                {
                    "role": "user",
                    "content": (
                        f"Write a caption for a short video. The file is named '{media_path.stem}'. "
                        f"{hint_text}"
                    ),
                },
            ],
            temperature=0.9,
            max_tokens=500,
            reasoning_effort="low",
        )

    return strip_reasoning(resp.choices[0].message.content)


# ---------- login ----------

def login():
    return ig_session.login(IG_USERNAME, IG_PASSWORD, SESSION_FILE, IG_SESSIONID)


# ---------- posting ----------

def upload(cl, media_path, caption, as_reel):
    """Returns the uploaded media object, or None on failure."""
    try:
        if media_path.suffix.lower() in IMAGE_EXTS:
            return cl.photo_upload(str(to_jpeg(media_path)), caption)
        if as_reel:
            return cl.clip_upload(str(media_path), caption)
        return cl.video_upload(str(media_path), caption)
    except PleaseWaitFewMinutes as e:
        print(f"Rate limited: {e}")
    except FeedbackRequired as e:
        print(f"Hit IG spam filter: {e}")
    except ClientError as e:
        print(f"Client error while uploading: {e}")
    except Exception as e:
        print(f"Unexpected error while uploading: {e}")
    return None


def archive(media_path):
    POSTED_DIR.mkdir(exist_ok=True)
    stamp = datetime.now(LOCAL_TZ).strftime("%Y%m%d_%H%M%S")
    dest = POSTED_DIR / f"{stamp}_{media_path.name}"
    shutil.move(str(media_path), str(dest))
    return dest


def post_next(args):
    """Pick the next file, build the caption, and post it. Returns True on success."""
    media_path = pick_next_media()
    if media_path is None:
        print(f"No media files found in '{POST_DIR}/'. Nothing to post.")
        return False

    print(f"Selected media: {media_path}")

    if args.caption:
        caption = args.caption
    else:
        try:
            groq_client = Groq(api_key=GROQ_API_KEY)
            caption = generate_caption(
                groq_client, media_path, hint=args.hint, hashtags=not args.no_hashtags
            )
        except Exception as e:
            print(f"Caption generation failed ({e}). Not posting.")
            return False
        if not caption:
            print("Model returned an empty caption. Not posting.")
            return False

    print(f"\nCaption:\n{caption}\n")

    if args.dry_run:
        print("Dry run: nothing was posted.")
        return True

    cl = login()
    result = upload(cl, media_path, caption, args.reel)
    if TMP_JPG_PATH.exists():
        TMP_JPG_PATH.unlink()

    if result is None:
        print("Upload failed. The file was left in place so it can be retried.")
        return False

    print(f"Posted successfully (media pk: {result.pk}).")
    try:
        shared_context.add_post(caption, args.hint, result.pk)
    except Exception as e:
        print(f"Couldn't save post context ({e}), continuing.")
    print(f"Moved to {archive(media_path)}")
    return True


# ---------- scheduling ----------

def parse_at(value):
    try:
        dt = datetime.strptime(value, "%Y-%m-%d %H:%M")
    except ValueError:
        sys.exit('--at must look like "2026-10-01 19:30" (24h, Asia/Jakarta time).')
    return dt.replace(tzinfo=LOCAL_TZ)


def next_daily_occurrence(hhmm, jitter_minutes=0):
    try:
        hour, minute = map(int, hhmm.split(":"))
        assert 0 <= hour < 24 and 0 <= minute < 60
    except Exception:
        sys.exit("--daily must look like HH:MM (24h), e.g. 19:30")

    now = datetime.now(LOCAL_TZ)
    target = now.replace(hour=hour, minute=minute, second=0, microsecond=0)
    if jitter_minutes:
        target += timedelta(minutes=random.uniform(-jitter_minutes, jitter_minutes))
    if target <= now:
        target = now.replace(hour=hour, minute=minute, second=0, microsecond=0) + timedelta(days=1)
        if jitter_minutes:
            target += timedelta(minutes=random.uniform(-jitter_minutes, jitter_minutes))
    return target


def wait_until(target):
    """Sleep in short chunks so Ctrl+C stays responsive and the countdown is visible."""
    print(f"Waiting until {target.strftime('%Y-%m-%d %H:%M:%S %Z')} ... (Ctrl+C to cancel)")
    while True:
        remaining = (target - datetime.now(LOCAL_TZ)).total_seconds()
        if remaining <= 0:
            return
        time.sleep(min(remaining, 60))


# ---------- main ----------

def main():
    parser = argparse.ArgumentParser(description="Post to Instagram now or on a schedule, with an AI-generated caption.")
    when = parser.add_mutually_exclusive_group()
    when.add_argument("--at", type=str, help='One-off schedule, "YYYY-MM-DD HH:MM" in Asia/Jakarta time.')
    when.add_argument("--daily", type=str, help="Post one file every day at HH:MM (Asia/Jakarta) until the folder is empty.")
    parser.add_argument("--jitter", type=int, default=0, help="With --daily: randomize the time by +/- N minutes.")
    parser.add_argument("--hint", type=str, default=None, help="Extra context for the caption model.")
    parser.add_argument("--caption", type=str, default=None, help="Use this caption instead of generating one.")
    parser.add_argument("--no-hashtags", action="store_true", help="Generate captions without hashtags.")
    parser.add_argument("--reel", action="store_true", help="Post videos as Reels instead of regular video posts.")
    parser.add_argument("--dry-run", action="store_true", help="Generate and print the caption, but don't post.")
    args = parser.parse_args()

    if not args.dry_run and not IG_PASSWORD:
        sys.exit("Set the IG_PASSWORD environment variable first.")
    if not args.caption and not GROQ_API_KEY:
        sys.exit("Set the GROQ_API_KEY environment variable first (or pass --caption).")

    # Fail early if there's nothing to post, instead of after a long wait.
    if pick_next_media() is None:
        sys.exit(f"No media files found in '{POST_DIR}/'. Add a jpg/png/mp4 there first.")

    if args.daily:
        while True:
            target = next_daily_occurrence(args.daily, args.jitter)
            wait_until(target)
            ok = post_next(args)
            if pick_next_media() is None:
                print("Folder is empty, stopping the daily schedule.")
                break
            if not ok:
                print("Post failed; will try again at the next scheduled time.")
    elif args.at:
        target = parse_at(args.at)
        if target <= datetime.now(LOCAL_TZ):
            sys.exit("That time is already in the past (Asia/Jakarta time).")
        wait_until(target)
        post_next(args)
    else:
        post_next(args)


if __name__ == "__main__":
    main()
